name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docker
        uses: actions/checkout@v3
        run: docker build . --file Dockerfile --tag flaskend:$(date +%s)
